name: Update Data

on:
    workflow_dispatch:
    schedule:
        # Every hour
      - cron: '0 * * * *'
    push: 
        paths: 
            - 'data/**'
            - '.github/workflows/data.yml'
            - 'scrape/**'

permissions:
  contents: write
  
jobs:
  data:
    name: Check the repos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
        
      - run: |
            git config --global user.name "Update Data"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: bun scrape/images.ts

